### ISSUE TITLE
fix dependency issue

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-daemon#17]
vendorcheck gives error because `hardware-wallet-go` has submodule `hardware-wallet-protob` which generates code when the command `make proto` is executed therefore the code is not vendored when using dep

**Comment by therealssj** [comment]
I could not get `dep` to initialise a submodule.
I have opened an [issue](https://github.com/golang/dep/issues/2146) in the project repo explaining what the issue but a reply could take day so the only solution i can think of is

- Remove messages submodule from hw-go
- Add a `go:generate` command in the protob just like i have done [here](https://github.com/therealssj/hardware-wallet-protob/tree/master/go) for testing to generate the proto files.
- Add protob a dep dependency in hw-go and hw-daemon, pinned to a specific commit
- We can choose to push to the generated proto files in the vendored directory. It doesn't change much.

**Comment by gz-c** [comment]
Push the generated proto files
