### ISSUE TITLE
The process closes if a request arrives before the previous one is completed

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-daemon#44]
**Describe the bug**
When the daemon receives an API request, it does not respond immediately, but after some delay. This is especially evident when the user must confirm the operation on the device: the daemon responds only after the user has accepted or rejected the operation.

If the daemon receives a new request during this waiting period (in other words, before answering the previous request), the process closes with an error.

**Environment information:**

- OS: Windows 10
- Platform: X86
- Firmware Version: ab2e80c

**Steps to Reproduce**
I tested the problem by following these steps:
1) Connect the hw wallet and open the daemon
2) Call the `/wipe` endpoint and do nothing in the device
3) Call the `/wipe` endpoint again, before the previous `/wipe` call had responded and while the device is still waiting for user input.

After step 3, the daemon will close. It may have to be done more than once, but it usually works the first time.

The calls can be to another endpoints, not necessarily `/wipe`. I tried `/set_pin_code` too.

**Actual behavior**
The dameon closes with an error. The output is not always the same. An examples is:
![daemon](https://user-images.githubusercontent.com/34079003/55991933-5cd87a80-5c79-11e9-9ea6-a97e2ec56a89.png)
Sometimes the output is quite long.

**Expected behavior**
The daemon should handle the problem and not close.

**Additional context**
None

**Possible implementation**
None

**Comment by Senyoret1** [comment]
I just wrote some code for calling the `/cancel` endpoint if the user waits more than 50 seconds to confirm the operations (to avoid some timeout problems) and the problem appears in that case too.

**Comment by therealssj** [comment]
The daemon handles the `ButtonAck` internally so the wait till user presses a button is expected. 
I can't get the daemon to reproduce this at all. 

What is that firmware version?

**Comment by Senyoret1** [comment]
Yeah, the first part is expected behavior, I added it only to give context. The real problem is the unexpected termination of the process.

The firmware version I added is the commit in the hardware wallet repo (it is the lastest commit in develop at this time).

As you could not reproduce the problem, I tried again using updated versions of the daemon and go cli, but the problem continued. Because of that, I then tested more in deep and found this:

1) Testing in Windows, using the steps I mentioned in the first message, the problem continued.

2) As you are not using Windows, I tried the same procedure using Linux, to see if the problem is present there too. The result was that the problem is not pesent in Linux, so maybe it's also not present in MacOS. What happens in Linux is that, after calling the endpoind for the second time, the first request is cancelled with result 500 and “hid: device closed” is returned as the result message (the daemon continues running normally):
![linux](https://user-images.githubusercontent.com/34079003/56066379-8f4fa980-5d45-11e9-8a12-ad38bb848703.png)

3) After the previous test, it became clear that the problem is present only in Windows, but not if the problem is in the daemon or the Go cli, so I tried the same procedure using it. In Linux, calling the endpoint for the second time caused the second call to fail with this error:
![linux-go](https://user-images.githubusercontent.com/34079003/56066387-95de2100-5d45-11e9-855c-7463aefc1be4.png)

4) After testing in Linux, I tried using the Go cli in Windows and the result was different. In Windows, calling the endpoint for the second time caused the first call to finist with an error:
![win-go](https://user-images.githubusercontent.com/34079003/56066390-9aa2d500-5d45-11e9-9b59-3f1e7b2cbd4a.png)

After all this, I can tell you that the problem is only in Windows and that the Go cli reacts differently to the situation in Linux and Windows, which could be the reason why the daemon also reacts differently in the two operating systems. I’m sorry for not being able to give you more specific details at this time, but I hope this information could be useful for you as a guide to know where the problem might be.

**Comment by jdknives** [comment]
@therealssj should this be closed?

**Comment by therealssj** [comment]
fixed in https://github.com/skycoin/hardware-wallet-go/pull/124
