### ISSUE TITLE
Hardware Daemon Implementation

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-daemon#5]
### Goal
- The daemon replaces the nodejs usbhid integration method using the electron wallet
- The daemon provides an HTTP API
- The clients will communicate over HTTP to the daemon, to access the hardware wallet
- The HTTP API should use Swagger to generate client code automatically (#1 )

The daemon is just a stripped down implementation of the skycoin core daemon with similar config system.
The default port is `9510`( can be changed if required )

### Implementation
**Main Endpoints**
These are the main hardware wallet operations

- [x] `/api/generateAddresses`
- [x] `/api/applySettings`
- [x] `/api/backup`
- [x] `/api/cancel`
- [x] `/api/checkMessageSignature`
- [x] `/api/features`
- [x] `/api/generateMnemonic`
- [x] `/api/recovery`
- [x] `/api/setMnemonic`
- [x] `/api/setPinCode`
- [x] `/api/signMessage`
- [x] `/api/transactionSign`
- [x] `/api/wipe`
- [x] `/updateFirmware`

**Intermediate Endpoints**
These are for intermediate operations when calling a `main` endpoint. E.g `Pin Request` 

The server returns a response telling what kind of intermediate operation it has received from the hardware wallet so the frontend can display accordingly whatever is required in the gui e.g a textbox for pin input etc.

- [x] `/api/intermediate/pinmatrix`
- [x] `/api/intermediate/passphrase`
- [x] `/api/intermediate/word`

> ButtonAck requests are handled directly without any intermediate request

### Testing
**Unit Tests**
- [x] `/api/generateAddresses`
- [x] `/api/applySettings`
- [x] `/api/backup`
- [x] `/api/cancel`
- [x] `/api/checkMessageSignature`
- [x] `/api/features`
- [x] `/api/generateMnemonic`
- [x] `/api/recovery`
- [x] `/api/setMnemonic`
- [x] `/api/setPinCode`
- [x] `/api/signMessage`
- [x] `/api/transactionSign`
- [x] `/api/wipe`
- [x] `/api/updateFirmware`

**Comment by olemis** [comment]
I'd rather include a version prefix since the beginning e.g. `/v1/wipe` , etc ...

**Comment by therealssj** [comment]
implemented in #8
