### ISSUE TITLE
Report the errors with LIBUSB in /available

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-daemon#53]
**Feature description**
Sometimes, after using the daemon for a while, the api endpoints start responding with error 500 and the LIBUSB_ERROR_OTHER message. From that moment the daemon is no longer usable, so it is possible to use that error message to know that there is an error with the daemon.

However, the `/available` endpoint does not return that error. Instead, when the error happens the `/available` endpoint simply start to always return `false`.

**Is your feature request related to a problem? Please describe.**
As stated above, after using the daemon for a while, the api endpoints start responding with error 500 and the LIBUSB_ERROR_OTHER message. When those errors start to appear, it is necessary to restart the daemon.

**Describe the solution you'd like**
When there are problems with LIBUSB, the `/available` endpoint should also return error 500 with the LIBUSB_ERROR_OTHER message. In fact, when the error is present, the LIBUSB_ERROR_OTHER message is shown in the console output, but is not sent as part of the http response.

**Describe alternatives you've considered**
None

**Additional context**
None

**Possible implementation**
None

**Comment by therealssj** [comment]
@olemis do you know what this LIBUSB error is?
If the daemon is erroring out like that after running for a while then it is a big problem
