### ISSUE TITLE
Signed macOS builds still complain when run

### ISSUE THREAD

**Issue by gz-c** [skycoin/hardware-wallet-daemon#90]
I still get the "untrusted program" warning from the system when I try to run the signed binary produced by the travis builds

**Comment by gz-c** [comment]
@therealssj are you sure that binary you shared with me was signed?

**Comment by gz-c** [comment]
>Was fixing the hardware wallet daemon code signing. Did lots of testing and research, but all failed. It seems we can sign the binary file directly, should either package it in a DMG file or pkg installer. Someone had the same problem, https://stackoverflow.com/questions/39811791/mac-os-gatekeeper-blocking-signed-command-line-tool/40295328#40295328.

**Comment by therealssj** [comment]
fixed in #96
